_target_: src.models.diffusion.lit_module.OMDiffLitModule

denoising_net:
  _target_: src.models.atomistic.AtomisticModel

  input_modules:
    one_hot:
      _target_: src.models.layers.features.OneHotEmbedding
      num_embeddings: ???
      embedding_dim: 256
      output_key: "node_states"
    fourier:
      _target_: src.models.layers.features.FourierFeatures
      in_features: 1
      out_features: 16
      input_key: "ts"
    combine:
      _target_: src.models.layers.features.Combine
      input_keys:
        - "node_states"
        - "ts"
      output_key: "node_states"
  backbone:
    _target_: src.models.backbones.equivnet.EquivNet
    hparams:
      _target_: src.models.backbones.equivnet.EquivNetHParams
      num_interactions: 5
      input_size: 288 # 256 + 2*16 for time
      node_size: 256
      edge_size: 64
    rbf_layer:
      _target_: src.models.layers.rbf.GaussianLinearRBFLayer
      n_features: 64
      max_distance: ???


  output_modules:
    readout:
      _target_: src.models.layers.readout.Readout
      net:
        _target_: src.models.layers.mlp.MLP
        input_dim: 256
        output_dim: ???
        hidden_dim: 256
      input_key: "node_states"
      output_key: "node_states"
      reduction: null
  additional_model_outputs:
    - "node_positions"

noise_model:
  _target_: src.models.diffusion.noise.model.MaskedNormalNoiseModel
  noise_schedule:
    _target_: src.models.diffusion.noise.schedule.FixedNoiseSchedule
    timesteps: 1000
  shape_mapping:
    node_positions: [ 3 ]
    node_features: ???
  center_keys: [ ]


train_loss_module:
  _target_: src.models.diffusion.loss.DiffusionL2Loss
  weights:
    node_positions: 1.0
    node_features: 0.25

val_test_loss_module:
  _target_: src.models.diffusion.loss.DiffusionL2Loss


optimizer:
  _target_: torch.optim.AdamW
  _partial_: true
  lr: 0.0001
  weight_decay: 1e-12
  amsgrad: true

diffusion_hp:
  _target_: src.models.diffusion.lit_module.DiffusionHParams
  val_sample_every: ???
  num_val_samples: ???
  sampling_batch_size: ???
  num_final_samples: ???
  yield_final_samples_every: ???
  scale_positions: ???

sampler:
  _target_: src.models.diffusion.sampling.conditional.MaskedSampler

connectivity_module:
  _target_: src.models.connectivity.ConnectedWithinCutoff
  cutoff: ???