_target_: src.models.regression.lit_module.TimeConditionedRegressorLitModule

regressor_net:
  _target_: src.models.atomistic.AtomisticModel

  input_modules:
    one_hot:
      _target_: src.models.layers.features.OneHotEmbedding
      num_embeddings: ???
      embedding_dim: 128
      output_key: "node_states"
    fourier:
      _target_: src.models.layers.features.FourierFeatures
      in_features: 1
      out_features: 16
      input_key: "ts"
    combine:
      _target_: src.models.layers.features.Combine
      input_keys:
        - "node_states"
        - "ts"
      output_key: "node_states"
  backbone:
    _target_: src.models.backbones.equivnet.EquivNet
    hparams:
      _target_: src.models.backbones.equivnet.EquivNetHParams
      num_interactions: 5
      input_size: 160 # 128 + 2*16 for time
      node_size: 128
      edge_size: 64
      with_edge_interactions: True
      update_node_positions: True
    rbf_layer:
      _target_: src.models.layers.rbf.GaussianLinearRBFLayer
      n_features: 64
      max_distance: ???

  output_modules:
    readout:
      _target_: src.models.layers.readout.Set2VecReadout
      score_net:
        _target_: src.models.layers.mlp.MLP
        input_dim: 128
        output_dim: 128
        hidden_dim: 128
      readout_net:
        _target_: src.models.layers.mlp.MLP
        input_dim: 128
        hidden_dim: 64
        output_dim: ???
      input_key: "node_states"
      output_key: ???
      splits_key: "num_nodes"


noise_model: ???

train_loss_module:
  _target_: src.models.regression.loss.TimeConditionedRegressorHuberLoss
  on_clean: false
  delta: ???

val_test_loss_module:
  _target_: src.models.regression.loss.TimeConditionedRegressorMSELoss
  on_clean: true


optimizer:
  _target_: torch.optim.AdamW
  _partial_: true
  lr: 0.0001
  weight_decay: 1e-12
  amsgrad: true

connectivity_module:
  _target_: src.models.connectivity.ConnectedWithinCutoff
  cutoff: ???